"""Pull profile info for the full handle list via TikTok Research API."""

import time
import csv
import os
import requests
from dotenv import load_dotenv
from auth import BASE_URL, auth_headers

load_dotenv()

HANDLES = [
    "_killpack___",
    "_thatonefitguy92",
    "11stacysmom",
    "2rawtooreal2",
    "3reecrossingradio",
    "90ssummerteen",
    "aaronparnas1",
    "absolutelynotmike",
    "alexandra_cascio",
    "alexhollings52",
    "allie_202_",
    "amandasmildtakes",
    "ana_kasparian",
    "andr3wsky",
    "andreiv.popescu",
    "angrymalevet",
    "anthonykort",
    "anttsinc",
    "arimelber",
    "astro_alaxandra",
    "auntiekilljoy",
    "averydaye",
    "bananadotgov",
    "beachlawyerpaul",
    "beautymrked",
    "beezay22",
    "bellas.brightspots",
    "benedetto.nayla",
    "bffrnews",
    "blackbeltbabe",
    "blackbeltbarrister",
    "blackkout___",
    "blackmarket.newsdaily",
    "blacktrustfundkids",
    "bloxcast_",
    "bobthedragqueen",
    "bodittletv",
    "boloudon",
    "bonnieoffwork",
    "booogierae",
    "bothsidesnews",
    "bottomupmedia",
    "brad.doggett",
    "bradbernsteinlaw",
    "briantylercohen",
    "brittanybee84",
    "brittanyepage",
    "browngirlgreen",
    "brranndo",
    "brynodc",
    "bsonblast",
    "btnewsroom",
    "c.a.i.t.l.y.n",
    "candaceoshow",
    "cannonsfodder",
    "carissaandclimate",
    "carvss.to",
    "cassie.willson",
    "cathypedrayes",
    "celticjumper",
    "cfh.unfiltered",
    "chasingoz",
    "cheerleader4change",
    "cheyennehuntca",
    "churchofthetrinitymcc",
    "cjtherhetorician",
    "clayy.edward",
    "cleoabram",
    "cohen.489",
    "colette8617",
    "columbiatwp",
    "commonsensegay",
    "concussiontalks.slp",
    "conservativeant1",
    "conservativebarbie",
    "conservativeguitarbabe",
    "conservativeimmigrant",
    "contraryian",
    "dailyplugusa",
    "dailywire",
    "damonimani",
    "dariarosereal",
    "davebondy",
    "davidarthurcrabb",
    "davidhundeyin",
    "davidpakmanshow",
    "debateher",
    "debtcollective",
    "defiance13",
    "definitelynotjackie",
    "dennis.fang",
    "deonjoseph22",
    "devinpolitics",
    "devonmurphyanderson",
    "dhjdnnn.hjkl",
    "dietrichfenske",
    "dinnerpancakes",
    "dixonwhite1",
    "djsoulchild0",
    "doctormike",
    "donlemon",
    "donnie.on.timeout",
    "doxielvr",
    "drannieobgyn",
    "dylan.page",
    "econwithsarah",
    "ed_in_burgh",
    "edwardmliger",
    "ej___1728",
    "emilyinyourphone",
    "emilysavesamericashow",
    "emma,jobsis",
    "end.yt.supremessy",
    "endeavorance",
    "erycsmyth",
    "etchaskej",
    "ethanlevinusa",
    "eumiexx",
    "ex3tecno",
    "fabrizioromano",
    "famousblonde",
    "fernandacortesx",
    "financialboffins",
    "follow_the_axolotl",
    "formichigan",
    "geohussar",
    "gibsonishere",
    "goodtrouble_",
    "grand_ole_evan",
    "gregisfire",
    "gregisfire_official",
    "gremloe",
    "guru_merc",
    "hal_for_ny__",
    "haleylickstein",
    "happyhippyian",
    "harryjsisson",
    "hayanomie",
    "heathergtv",
    "helloamericasup",
    "heresdarian",
    "hersocialtakes",
    "hey_molombo",
    "heyitstwig25",
    "historywithmrcho",
    "hopeyoufindyourdad",
    "iamcj__2",
    "iampoliticsgirl",
    "ilypierce",
    "immi.grateful",
    "instantnewsdaily",
    "itsalllpolitics__",
    "itsdeaann",
    "itslinklauren",
    "ittybitty_tara2",
    "ivehadit.tv",
    "j1027106",
    "jacobsimonsays",
    "jamellebouie",
    "jarretberenstein",
    "jaysworld411",
    "jborc33",
    "jddelay1017",
    "jeffery.mead",
    "jesscraven101",
    "joe_hubbard",
    "joepags",
    "joeycontino2",
    "johnny.harris",
    "johnstone.gregory",
    "joshualafazan",
    "joyreidofficial",
    "jrmajewski",
    "julesterpak",
    "julielouise1975",
    "jusnene",
    "justinthenickofcrime",
    "k_dub_h",
    "kaburbank",
    "kagan_dunlap",
    "kaivanshroff",
    "kayshmoneyy",
    "keccak256",
    "keibenet",
    "kellermankomedy",
    "kendallybrown",
    "king_millennial_ent2",
    "kingashleyann",
    "kingkhieu",
    "krassenstein",
    "krisgoldsmith85",
    "kristenzisek",
    "ladymisskay",
    "laissezfairelounge",
    "latoshamercado",
    "laysieeeb",
    "leejamiller",
    "leoexplains",
    "letsdiscusssomething",
    "lifegoalinvestments",
    "lindsayrousseau",
    "lisandravcomedy",
    "lisaremillard",
    "little.miss.independent",
    "lowlyfeleo",
    "lukebeasleyofficial",
    "lukebellinghausen",
    "magaliz84",
    "mahfuztalukder",
    "majorityreportfm",
    "marcus.dipaola",
    "matteo_il_pazzeo",
    "matthew_pridgen",
    "mattwalsh",
    "mattxiv",
    "mayorhaley",
    "mdg650hawk7thacct",
    "meghanelinor",
    "megynkellyshow",
    "mehdirhasan",
    "meidastouch",
    "melhamlett",
    "mia.taylor3.0",
    "mictheoryseries",
    "migrationfilms",
    "mikesippel21",
    "millennialmia",
    "minipapix",
    "modernday_esatosthenes",
    "molly0xfff",
    "mollybmcpherson",
    "mongtho.lac112",
    "mow3163",
    "mrglobaltoo",
    "mrs_unbreakable1",
    "mrsmisanthrope2",
    "mscocomisty",
    "mulligan.tv",
    "naenae_jonez3",
    "naorosreagiert",
    "nawalornoel",
    "nerdypinkpanda1",
    "nessadiosdado",
    "neurodivergent_nate",
    "newswithpat",
    "nickmatau",
    "nickshirleyy",
    "nikitadumptruck",
    "nooxynews_lordtimothais",
    "nooxynews_lordtimothias",
    "notjordanpeele",
    "notstanleytucci",
    "nottherealjohnnybananas",
    "notusreports",
    "np6ea7s1",
    "of_counsel",
    "off_jawaggon",
    "officialchriscillizza",
    "okiepatrior1776",
    "oldcardude",
    "omaragamyy",
    "oneogden",
    "othertopics",
    "outspoken_samantha",
    "pastorpauldrees",
    "patriotdadev3.0",
    "patriotic_em",
    "patrioticpeach",
    "patriotsperspective2.0",
    "pauletteonthemic",
    "pdavisjones",
    "pdspopculture",
    "pearlmania500",
    "pennylane.usa",
    "perezbrenna",
    "pettycrocker88",
    "philipdefranco",
    "phupha.z",
    "pinkmantaray",
    "potatoprincess123",
    "prestonstew",
    "prettypolitics101",
    "princess.paulai",
    "priyaee_",
    "prof..carlos.l..ga",
    "professor_baba_lloyd",
    "pullupspastapolitics",
    "pvanny_",
    "queenbee1268",
    "quickrundownhub",
    "rachel_mle",
    "raebil0626",
    "rark.muffalo",
    "rationalboomer",
    "ravennareport",
    "razorbladecactus",
    "rbreich",
    "real_talk_with_tom",
    "real.benshapiro",
    "realgodivagoddess",
    "realtalkus",
    "rebelnews",
    "rebmasel",
    "redblueandyou",
    "redwhiteandwtf",
    "republicanreflections",
    "revbrandanrobertson",
    "revdrcalebjlines",
    "revjacquijlewis",
    "revtimoth",
    "rhiannonjarred",
    "rhonerundown",
    "rileyluenews",
    "rubin_allergy",
    "s.cage2",
    "sagedoorkicker",
    "sambentley",
    "savannahhh.james",
    "savnews72",
    "scottcoopwood",
    "seanlinden1",
    "sench_ola",
    "sertitudesarah",
    "shannonsmith3239",
    "shannonsmith3239backup",
    "sheisntnice",
    "sie_sassy",
    "silentmiddlechild",
    "simpleblacktheory",
    "slaythegop",
    "southern.punk.3.0",
    "spencerhakimian",
    "spillthetea5507",
    "stephanies_universe",
    "strangesaunashow",
    "strongtherapy",
    "stuarth20",
    "tabithaspeaks",
    "takenaps_",
    "talkswithrowan",
    "tallgirl6234",
    "tangerine_trampoline",
    "teacher_in_nj",
    "teatime.with.chris",
    "tevin.m.davis",
    "thatdaneshguy",
    "thatferalhousewif",
    "thatopinionatedgirl3",
    "the_kamoka",
    "the.law.says.what",
    "the.sisofficial",
    "the.watchman98",
    "thebannedbeard13",
    "thecharliekirkshow",
    "theconsciouslee",
    "thefeministlawyer",
    "thegarbagequeen",
    "thehandsomeliberal",
    "thejeremiahpattersonshow",
    "thejfc",
    "thelocalprepper",
    "themedicarefamily",
    "themidnight123",
    "thenoaestrella",
    "theoldermillennial",
    "theplanker",
    "therealalaskanavenger",
    "therealathenak",
    "therealdoubledeemuva",
    "therealjustjen",
    "therealtabithaspeaks",
    "theresas_daughter",
    "therobbieharvey",
    "theyoungturks",
    "thotline_news",
    "tizzyent",
    "tnathan_lokius",
    "todaynews",
    "tok1nblackguy",
    "totalhypocrisy",
    "toureshow",
    "trashcaulin",
    "treyyingst",
    "tryingthisthat",
    "tuckercarlson",
    "txtrophyhuntfish",
    "unclejohn327",
    "underthedesknews",
    "unfadingsilence",
    "valentivideos.alt",
    "vance4pres",
    "vibecraftvoice",
    "waltonwisdom",
    "what.you.missed.today",
    "whatinclaynation",
    "whatsupcv",
    "whoiskingtrivv",
    "willz.talks",
    "wokenbrownie",
    "womeninamerica",
    "wyoplantbasedteacher",
    "xaviaer",
    "xyfcenter",
    "yenaakiiim",
    "ygxhufhj",
    "youcanbebothpodcast",
    "youngmercfire",
    "zach.costello6",
    "zachary.films",
    "zanageeartis",
]

OUTPUT_CSV = "complete_handle_info.csv"

PROFILE_FIELDS = [
    "display_name",
    "bio_description",
    "is_verified",
    "follower_count",
    "following_count",
    "likes_count",
    "video_count",
]

CSV_COLUMNS = [
    "handle",
    "display_name",
    "follower_count",
    "following_count",
    "likes_count",
    "video_count",
    "is_verified",
    "bio",
    "api_failed",
]


def get_user_info(username):
    resp = requests.post(
        f"{BASE_URL}/research/user/info/",
        headers={**auth_headers(), "Content-Type": "application/json"},
        json={"username": username},
        params={"fields": ",".join(PROFILE_FIELDS)},
    )
    if resp.status_code == 429:
        retry_after = int(resp.headers.get("Retry-After", 10))
        print(f"  Rate limited — waiting {retry_after}s")
        time.sleep(retry_after)
        return get_user_info(username)
    if not resp.ok:
        print(f"  Error {resp.status_code} for @{username}: {resp.text}")
        return None
    return resp.json().get("data", {})


def load_existing():
    """Load already-processed handles from the CSV if it exists."""
    existing = {}
    if os.path.exists(OUTPUT_CSV):
        with open(OUTPUT_CSV, newline="", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                existing[row["handle"]] = row
    return existing


def main():
    # Load existing data to skip already-processed handles
    existing = load_existing()
    existing_handles = set(existing.keys())

    to_process = [h for h in HANDLES if f"@{h}" not in existing_handles]
    print(f"=== {len(HANDLES)} total handles, {len(existing_handles)} already in CSV, {len(to_process)} to process ===")

    if not to_process:
        print("Nothing new to process.")
        return

    # Step 1: Pull profile info for new handles
    new_profiles = []
    for i, handle in enumerate(to_process, 1):
        print(f"[{i}/{len(to_process)}] @{handle}...")
        data = get_user_info(handle)
        if data:
            new_profiles.append({
                "handle": f"@{handle}",
                "display_name": data.get("display_name", ""),
                "follower_count": data.get("follower_count", 0),
                "following_count": data.get("following_count", 0),
                "likes_count": data.get("likes_count", 0),
                "video_count": data.get("video_count", 0),
                "is_verified": data.get("is_verified", False),
                "bio": data.get("bio_description", ""),
                "api_failed": 0,
            })
            print(f"  → {data.get('follower_count', '?')} followers")
        else:
            new_profiles.append({
                "handle": f"@{handle}",
                "display_name": "",
                "follower_count": 0,
                "following_count": 0,
                "likes_count": 0,
                "video_count": 0,
                "is_verified": False,
                "bio": "",
                "api_failed": 1,
            })
            print(f"  → skipped (no data)")

    # Step 2: Merge existing + new, write CSV in HANDLES order
    all_profiles = {**existing}
    for profile in new_profiles:
        all_profiles[profile["handle"]] = profile

    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_COLUMNS, extrasaction="ignore")
        writer.writeheader()
        for handle in HANDLES:
            key = f"@{handle}"
            if key in all_profiles:
                writer.writerow(all_profiles[key])

    total = len([h for h in HANDLES if f"@{h}" in all_profiles])
    print(f"\nDone. {total} accounts written to {OUTPUT_CSV} ({len(new_profiles)} new)")


if __name__ == "__main__":
    main()
